import Footer from '@/sections/Footer';
import Header from '@/sections/Header';
import Head from 'next/head';

export default function About() {
  return (
    <>
      <Head>
        <title>IndODish - About</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Footer />
    </>
  );
}
