import Footer from '@/sections/Footer';
import Header from '@/sections/Header';
import Head from 'next/head';
import BlogPost from '../sections/BlogPost';
import RecipePost from '../sections/RecipePost';

export default function Blog() {
  // Array of blog posts
  const blogPosts = [
    {
      id: 1,
      title: "Blog Post 1",
      content: "Content for Blog Post 1",
    },
    {
      id: 2,
      title: "Blog Post 2",
      content: "Content for Blog Post 2",
    },
    {
      id: 3,
      title: "Blog Post 3",
      content: "Content for Blog Post 3",
    },
  ];

  return (
    <>
      <Head>
        <title>IndODish - Blog</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />

      <main>
        {blogPosts.map((post) => (
          <BlogPost key={post.id} title={post.title} content={post.content} />
        ))}
        </main>

      <RecipePost/>
      <Footer />
    </>
  );
}
