import Head from 'next/head';
import Image from 'next/image';
import BatikBackground from '../../public/batik-background.webp';
import Header from '@/sections/Header';
import Footer from '@/sections/Footer';
import styles from '@/styles/pages/cart.module.scss';
import { AppDispatch, RootState } from '@/store/store';
import { useDispatch, useSelector } from 'react-redux';
import { useEffect } from 'react';
import { getCartItems } from '@/features/cartSlice';
import { Spinner } from '@chakra-ui/react';
import CartItemCard from '@/components/CartItemCard';

export default function Cart() {
  const dispatch = useDispatch<AppDispatch>();
  const { isLoading, error, cart } = useSelector(
    (state: RootState) => state.cart
  );

  useEffect(() => {
    dispatch(getCartItems());
  }, []);
  console.log(cart);
  return (
    <>
      <Head>
        <title>IndODish - Cart</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <h2 className={styles.header}>Your cart</h2>
      <div className={styles.container}>
        <main>
          {isLoading ? (
            <Spinner />
          ) : (
            <div>
              {cart.length > 0 ? (
                cart.map((item) => (
                  <CartItemCard
                    key={item.id}
                    id={item.id}
                    dishName={item.name}
                    quantity={item.quantity}
                    price={item.price}
                  />
                ))
              ) : (
                <p style={{ color: '#fff', padding: '2rem 1rem' }}>
                  Nothing...
                </p>
              )}
              <Image
                className={styles.batik_background}
                src={BatikBackground}
                alt='Batik Background'
                fill
              />
            </div>
          )}
        </main>
      </div>
      <Footer />
    </>
  );
}
