import Footer from '@/sections/Footer';
import Header from '@/sections/Header';
import Head from 'next/head';
import CuisineDesc from '@/sections/CuisineDesc';
import RecipePost from '../sections/RecipePost';
import NearbyRestaurant from '@/sections/NearbyRestaurant';

export default function Cuisine() {
  return (
    <>
      <Head>
        <title>IndODish - Cuisine</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <CuisineDesc />
      
      <NearbyRestaurant />
      <RecipePost recipe={{}} />

      <Footer />
    </>
  );
}
