import Head from 'next/head';
import Header from '@/sections/Header';
import Footer from '@/sections/Footer';
import Hero from '@/sections/Hero';
import BrowseLocation from '@/sections/BrowseLocation';
import MostPopular from '@/sections/MostPopular';
import styles from '@/styles/pages/Home.module.scss';

export default function Home() {
  return (
    <>
      <Head>
        <title>IndODish - Home</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Hero />
      <BrowseLocation />
      <MostPopular />
      <Footer />
    </>
  );
}
