import { useState, useEffect } from 'react';
import Router from 'next/router';
import { useDispatch, useSelector } from 'react-redux';
import { AppDispatch, RootState } from '../store/store';
import { signUp, signIn } from '@/features/authSlice';
import Image from 'next/image';
import Head from 'next/head';
import IndODishLogo from '@/components/IndODishLogo';
import styles from '@/styles/pages/SignUp.module.scss';
import { Playfair_Display } from 'next/font/google';
import {
  Text,
  Button,
  FormControl,
  FormLabel,
  Input,
  FormHelperText,
  InputGroup,
  InputRightElement,
  Spinner,
} from '@chakra-ui/react';
import BatikBackground from '../../public/batik-background.webp';
import Link from 'next/link';

const playfairDisplay = Playfair_Display({
  weight: ['400', '600'],
  subsets: ['latin'],
});

export default function SignUp() {
  const dispatch = useDispatch<AppDispatch>();
  const { isLoading, error, user } = useSelector(
    (state: RootState) => state.auth
  );
  const [firstName, setFirstName] = useState('');
  const [lastName, setLastName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [passwordConfirmation, setPasswordConfirmation] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [showPasswordConfirmation, setShowPasswordConfirmation] =
    useState(false);

  const handleShowPasswordButton = () => setShowPassword(!showPassword);
  const handleShowPasswordConfirmationButton = () =>
    setShowPasswordConfirmation(!showPasswordConfirmation);

  const handleSignUp = () => {
    dispatch(
      signUp({ firstName, lastName, email, password, passwordConfirmation })
    );
  };

  useEffect(() => {
    if (user) {
      dispatch(signIn({ email, password }))
        .catch(() => {
          Router.push('/sign-in');
        })
        .finally(() => {
          Router.push('/');
        });
    }
  }, [user]);

  return (
    <>
      <Head>
        <title>IndODish - Sign In</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={`${styles.container} ${playfairDisplay.className}`}>
        <header>
          <IndODishLogo color={'#ffffff'} />
          <h2>Sign Up</h2>
        </header>
        <main>
          <FormControl>
            <FormLabel mt={4} style={{ color: '#ffffff' }}>
              First Name
            </FormLabel>
            <Input
              mt={2}
              size='lg'
              type='text'
              variant='filled'
              focusBorderColor='#e37300'
              value={firstName}
              onChange={(e) => setFirstName(e.target.value)}
              placeholder='First Name'
              _focus={{
                backgroundColor: '#ffffff',
              }}
            />
            <FormLabel mt={4} style={{ color: '#ffffff' }}>
              Last Name
            </FormLabel>
            <Input
              mt={2}
              size='lg'
              type='text'
              variant='filled'
              focusBorderColor='#e37300'
              value={lastName}
              onChange={(e) => setLastName(e.target.value)}
              placeholder='Last Name'
              _focus={{
                backgroundColor: '#ffffff',
              }}
            />
            <FormLabel mt={4} style={{ color: '#ffffff' }}>
              Email address
            </FormLabel>
            <Input
              mt={2}
              size='lg'
              type='email'
              variant='filled'
              focusBorderColor='#e37300'
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder='Email Address'
              _focus={{
                backgroundColor: '#ffffff',
              }}
            />
            <FormLabel mt={4} style={{ color: '#ffffff' }}>
              Password
            </FormLabel>
            <InputGroup mt={2}>
              <Input
                size='lg'
                type={showPassword ? 'text' : 'password'}
                variant='filled'
                focusBorderColor='#e37300'
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder='Password'
                _focus={{
                  backgroundColor: '#ffffff',
                }}
              />
              <InputRightElement width='4.5rem' marginBlock='1' marginEnd='2'>
                <Button
                  h='2rem'
                  size='lg'
                  onClick={handleShowPasswordButton}
                  variant='solid'
                  colorScheme='yellow'
                >
                  {showPassword ? 'Hide' : 'Show'}
                </Button>
              </InputRightElement>
            </InputGroup>
            <FormLabel mt={4} style={{ color: '#ffffff' }}>
              Password Confirmation
            </FormLabel>
            <InputGroup mt={2}>
              <Input
                size='lg'
                type={showPasswordConfirmation ? 'text' : 'password'}
                variant='filled'
                value={passwordConfirmation}
                onChange={(e) => setPasswordConfirmation(e.target.value)}
                focusBorderColor='#e37300'
                placeholder='Password Confirmation'
                _focus={{
                  backgroundColor: '#ffffff',
                }}
              />
              <InputRightElement width='4.5rem' marginBlock='1' marginEnd='2'>
                <Button
                  h='2rem'
                  size='lg'
                  onClick={handleShowPasswordConfirmationButton}
                  variant='solid'
                  colorScheme='yellow'
                >
                  {showPasswordConfirmation ? 'Hide' : 'Show'}
                </Button>
              </InputRightElement>
            </InputGroup>
            <Button
              mt={12}
              type='submit'
              width={'100%'}
              colorScheme='orange'
              onClick={handleSignUp}
            >
              {isLoading ? <Spinner /> : 'Sign up with Email'}
            </Button>
          </FormControl>
          <Text
            style={{ color: '#fff', textAlign: 'center', marginTop: '2rem' }}
          >
            Already have an account ?
            <Link
              style={{ color: '#f8d72a', marginLeft: '1rem' }}
              href='/sign-in'
            >
              Login here
            </Link>
          </Text>
          <Image
            className={styles.batik_background}
            src={BatikBackground}
            alt='Batik Background'
            fill
          />
        </main>
      </div>
    </>
  );
}
