import Footer from '@/sections/Footer';
import Header from '@/sections/Header';
import Head from 'next/head';
import CuisineDesc from '@/sections/CuisineDesc';
import RecipePost from '@/sections/RecipePost';
import NearbyRestaurant from '@/sections/NearbyRestaurant';
import { AppDispatch, RootState } from '@/store/store';
import { useDispatch, useSelector } from 'react-redux';
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import { getCuisine } from '@/features/cuisineSlice';
import { Spinner } from '@chakra-ui/react';

export default function Cuisine() {
  const dispatch = useDispatch<AppDispatch>();
  const { isLoading, error, dish } = useSelector(
    (state: RootState) => state.dish
  );
  const router = useRouter();

  useEffect(() => {
    if (!router.isReady) {
      return;
    }

    dispatch(getCuisine(router.query.dish_name as string));
  }, [router.isReady]);

  return (
    <>
      <Head>
        <title>IndODish - Cuisine</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />

      {isLoading && error == null ? (
        <Spinner />
      ) : (
        <CuisineDesc
          name={dish.name}
          description={dish.description}
          price={dish.price}
        />
      )}

      <NearbyRestaurant />
      <RecipePost/>

      <Footer />
    </>
  );
}
